"""Default domain allowlist for sandboxed package-manager and VCS traffic."""

from __future__ import annotations

DEFAULT_ALLOWED_DOMAINS: tuple[str, ...] = (
    "*.cloudflarestorage.com",
    "*.docker.com",
    "*.docker.io",
    "*.googleapis.com",
    "*.githubusercontent.com",
    "*.gvt1.com",
    "*.yarnpkg.com",
    "alpinelinux.org",
    "anaconda.com",
    "archive.ubuntu.com",
    "bitbucket.org",
    "crates.io",
    "debian.org",
    "files.pythonhosted.org",
    "ghcr.io",
    "*.github.com",
    "github.com",
    "gitlab.com",
    "golang.org",
    "index.crates.io",
    "maven.org",
    "nodejs.org",
    "npmjs.com",
    "npmjs.org",
    "nuget.org",
    "proxy.golang.org",
    "pypi.org",
    "pypi.python.org",
    "pythonhosted.org",
    "quay.io",
    "registry.npmjs.org",
    "registry.yarnpkg.com",
    "repo.maven.apache.org",
    "rubygems.org",
    "rustup.rs",
    "security.ubuntu.com",
    "static.crates.io",
    "static.rust-lang.org",
    "sum.golang.org",
    "ubuntu.com",
    "yarnpkg.com",
)
